{% set name = "alto-dev" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/alto-dev-{{ version }}.tar.gz
  sha256: 011167fd8a37999e9c5fd817d76b3c4f2a98ff8a7a9d5ba4cb3e8d1754457d83

build:
  entry_points:
    - alto = alto.main:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=41.1.0
    - pip
  run:
    - python >={{ python_min }}
    - astor >=0.7
    - boto3 >=1
    - boto3-stubs >=1.34
    - botocore >=1
    - click >=8
    - pyyaml >=6
    - requests >=2
    - jinja2 ==3.1.2
    - markupsafe >=2.0
    - coolname >=2.2
    - shortuuid >=1.0
    - rich-click >=1.6.1
    - beautifulsoup4 >=4.12

    # For boto3-stubs[essential]
    - mypy_boto3_cloudformation
    - mypy_boto3_dynamodb
    - mypy_boto3_ec2
    - mypy_boto3_lambda
    - mypy_boto3_rds
    - mypy_boto3_dynamodb
    - mypy-boto3-s3
    - mypy_boto3_sqs

test:
  imports:
    - alto
  commands:
    - pip check
    - alto --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/runprism/alto
  doc_url: https://alto.mintlify.app
  summary: Run any code on the cloud, instantly.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
